### ISSUE TITLE
Babel 6.8.0  not working

### ISSUE THREAD

**Issue by ufoqhmdt** [kriasoft/babel-starter-kit#22]
always tips :

```

module.js:341
    throw err;
    ^

Error: Cannot find module 'core-js/library/fn/symbol/iterator'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/ufo/workspaces/babel-starter-kit/node_modules/.npminstall/babel-runtime/6.6.1/babel-runtime/core-js/symbol/iterator.js:1:93)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```
##

**Comment by koistya** [comment]
@ufoqhmdt what version of `npm` are you using?

**Comment by raoenhui** [comment]
I've met the issue too
node -v v4.4.5
npm -v 2.15.5

**Comment by arnoutc** [comment]
I have this issue too.  However, I have 
babel-core -v 6.17.0
node -v 4.4.4
npm -v 3.10.8
Darwin MacBook-Pro.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32.3/RELEASE_X86_64 x86_64   (Sierra OSX)

I am executing this command: ./node_modules/.bin/babel-node ./index.js
